version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_DEV}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_DEV}
      POSTGRES_DB: ${DATABASE_NAME_DEV}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - junetwork
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/var/lib/redis/data
    networks:
      - junetwork
networks:
 junetwork:
    driver: bridge

# COMMANDS: docker-compose up -d, docker-compose down
