name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: node:18
    services:
      postgres-test:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{secrets.DATABASE_USER_TEST}}
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD_TEST}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME_TEST}}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis-test:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check standard
        run: npm run standard
      - name: Make the environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: ${{secrets.NODE_ENV}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_HOST_TEST: ${{secrets.DATABASE_HOST_TEST}}
          envkey_DATABASE_PORT_TEST: ${{secrets.DATABASE_PORT_TEST}}
          envkey_DATABASE_USER_TEST: ${{secrets.DATABASE_USER_TEST}}
          envkey_DATABASE_PASSWORD_TEST: ${{secrets.DATABASE_PASSWORD_TEST}}
          envkey_DATABASE_NAME_TEST: ${{secrets.DATABASE_NAME_TEST}}
          envkey_EMAIL: ${{secrets.EMAIL}}
          envkey_EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          envkey_TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
          envkey_TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
          envkey_TWILIO_MESSAGING_SERVICE_SID: ${{secrets.TWILIO_MESSAGING_SERVICE_SID}}
          envkey_TWILIO_WHATSAPP: ${{secrets.TWILIO_WHATSAPP}}
          envkey_TOKEN_SECRET_KEY: ${{secrets.TOKEN_SECRET_KEY}}
          envkey_SERVER_URL: ${{secrets.SERVER_URL}}
          fail_on_empty: true
      - name: Run migrations
        run: npm run db:migrate:test
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    needs: CI
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: Execute remote commands via ssh
        # This step uses the ssh key stored in the SSH_KEY secret to access the server
        # and execute necessary commands to deploy the application
