name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuos Integration
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Make the environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NODE_ENV: ${{secrets.NODE_ENV}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_DATABASE_HOST_PROD: ${{secrets.DATABASE_HOST_PROD}}
          envkey_DATABASE_PORT_PROD: ${{secrets.DATABASE_PORT_PROD}}
          envkey_DATABASE_USER_PROD: ${{secrets.DATABASE_USER_PROD}}
          envkey_DATABASE_PASSWORD_PROD: ${{secrets.DATABASE_PASSWORD_PROD}}
          envkey_DATABASE_NAME_PROD: ${{secrets.DATABASE_NAME_PROD}}
          envkey_EMAIL: ${{secrets.EMAIL}}
          envkey_EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          envkey_REDIS_HOST: ${{secrets.REDIS_HOST}}
          envkey_REDIS_PORT: ${{secrets.REDIS_PORT}}
          envkey_TWILIO_ACCOUNT_SID: ${{secrets.TWILIO_ACCOUNT_SID}}
          envkey_TWILIO_AUTH_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
          envkey_TWILIO_MESSAGING_SERVICE_SID: ${{secrets.TWILIO_MESSAGING_SERVICE_SID}}
          envkey_TWILIO_WHATSAPP: ${{secrets.TWILIO_WHATSAPP}}
          envkey_TOKEN_SECRET_KEY: ${{secrets.TOKEN_SECRET_KEY}}
          envkey_SERVER_URL: ${{secrets.SERVER_URL}}
          fail_on_empty: true
      - name: Check standard
        run: npm run standard
      - name: Run migrations
        run: npm run db:migrate:test
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
  CD:
    name: Continuos Deployment
    runs-on: ubuntu-latest
    needs: CI
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Execute remote commands via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_PROD }}
          username: ${{ secrets.AWS_USER_PROD }}
          key: ${{ secrets.AWS_KEY_PROD }}
          script: PATH=$PATH:/usr/bin && sh deploy_main.sh
